### ISSUE TITLE
PHR doesn't load in IE 11

### ISSUE THREAD

**Issue by juliashulga** [PulseTile/PulseTile-React-Core#176]

**Comment by juliashulga** [comment]
![awesomescreenshot-2018-06-21t08-02-41-740z](https://user-images.githubusercontent.com/39296691/41706115-a508e79a-7543-11e8-8ec7-cc4ebc8380c3.gif)

**Comment by kuvakina** [comment]
Update on 05/07/2018

At the moment IE11 can load Login page. 
![176](https://user-images.githubusercontent.com/40596171/42315434-177f815a-8050-11e8-919d-8f9ba8479328.png)

But when we input email/password and click Sign in we are followed to the error page:
![176_bug_2_ token](https://user-images.githubusercontent.com/40596171/42315419-0eadb8d0-8050-11e8-8159-d04943ea4198.png)

Oleg looking into this issue, to find where can be the problem.

**Comment by kuvakina** [comment]
UPD:

IE11: We can log in now, log out and also force logout after session expired, but sometimes loading takes too much time (around 7-20 sec). And sometimes (most of the time) you have to reload the page or clear cookies to log in / log out:

https://drive.google.com/file/d/1yaPEqpJrHMovg9XNJ8gm9kC3_cwudcfs/view?usp=sharing

We are looking at how to fix it.

**Comment by tony-shannon** [comment]
thank you, I suggest all these IE11 issues are linked

**Comment by kuvakina** [comment]
Yes, I'll link them as for now IE11 won't work correctly.

- [ ] https://github.com/PulseTile/PulseTile-React-Core/issues/140 Sigh out requires to reload page or to clean cookies 

- [ ] https://github.com/PulseTile/PulseTile-React-Core/issues/170 To sing in / sigh out requires to reload page or to clean cookies

- [ ] https://github.com/PulseTile/PulseTile-React-Core/issues/153 Expired session shows incorrect message and requires to reload page or to clean cookies

**Comment by kuvakina** [comment]
@tony-shannon 

PHR loads (but it's takes time) in IE11, but there is another issue now. Loaded PHR looks like this: https://www.screencast.com/t/fKtpSYDpGPe

The error is:
SCRIPT438: Object does not support property or method "startsWith"
main.js (1,1153597)

Should we ask Oleg to look into this issue later?

**Comment by kuvakina** [comment]
Created a new issue for this bug. Could we move this issue to Done?

**Comment by tony-shannon** [comment]
Hi @kuvakina, what new issue? please reference here

**Comment by kuvakina** [comment]
@tony-shannon for the bug I created issue #236

**Comment by PhilBarrett** [comment]
Closed, 236 open in place
